In [1]:
print(3*4)

12


In [2]:
import numpy as np

In [3]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

In [4]:
a = np.array([[1, 2, 3],[4, 5, 6]])

In [5]:
a.shape()

TypeError: 'tuple' object is not callable

In [ ]:
a.shape

In [ ]:
print('hello')

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a

In [ ]:
a[0]

In [ ]:
a[4]

In [ ]:
a[0]=78

In [ ]:
a

this is called slicing

In [ ]:
a[:2]

In [ ]:
a[2:]

In [ ]:
b=a[3:]

In [ ]:
b

This is a test

In [ ]:
b[3]

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

In [ ]:
a.ndim

In [ ]:
n.shape

In [ ]:
a.shape #3 rows and 4 columns

In [ ]:
len(a.shape) # rows and columns

In [ ]:
a.size #total number of elements in the array

In [ ]:
a= [44,23]
a.shape
len(a.shape)
a.size

In [ ]:
a= ([44,23])
a.shape
len(a.shape)
a.size

In [ ]:
a= np.array([44,23])
a.shape
len(a.shape)
a.size

In [ ]:
a.shape # 2 columns

In [ ]:
len(a.shape) #1 row

In [ ]:
a.size

In [ ]:
a= np.array([44,23,99])
print(a.shape)
print(len(a.shape))
print(a.size)

In [ ]:
a= np.array([44,23,99],[11,22])
print(a.shape)
print(len(a.shape))
print(a.size)

In [ ]:
a= np.array([[44,23,99],[11,22,33]])
print(a.shape)
print(len(a.shape))
print(a.size)

In [ ]:
a= np.array([[44,23,99],[11,22,33],[44,55,66]])
print(a.shape)
print(len(a.shape))
print(a.size)

In [ ]:
a= np.array([[44,23,99],[11,22,33],[44,55,66]],[1,2,3])
print(a.shape)
print(len(a.shape))
print(a.size)

In [ ]:
a= np.array([1,2,3],[11,22,33],[44,55,66])
print(a.shape)
print(len(a.shape))
print(a.size)

Following is a 3 dimensional array - [[[ inidcates dimension
shape : (2, 2, 3) = 2*2*3 = 12 elements  

In [ ]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a)
print("============")
print("shape :" , a.shape)
print("============")
print("len(a.shape) :" , len(a.shape))
print("============")
print("a.size" , a.size)
print("============")

In [ ]:
a = np.array([1,2])
print(a.shape)
print(len(a.shape))
print(a.size)

In [ ]:
a = np.array([[1,2],[3,4]])
print(a)
print("============")
print("shape :" , a.shape)
print("============")
print("len(a.shape) :" , len(a.shape))
print("============")
print("a.size" , a.size)
print("============")

In [ ]:
a = np.array([[[1,2],[3,4]],[1,2],[3,4]])
print(a)
print("============")
print("shape :" , a.shape)
print("============")
print("len(a.shape) :" , len(a.shape))
print("============")
print("a.size" , a.size)
print("============")

In [ ]:
a = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(a)
print("============")
print("shape :" , a.shape)
print("============")
print("len(a.shape) :" , len(a.shape))
print("============")
print("a.size" , a.size)
print("============")

4 pairs of X-Y seperated by space


In [ ]:
a = np.array([[[[1,2],[3,4]],[[1,2],[3,4]]],[[[1,2],[3,4]],[[1,2],[3,4]]]])
print(a)
print("============")
print("shape :" , a.shape)
print("============")
print("len(a.shape) :" , len(a.shape))
print("============")
print("a.size" , a.size)
print("============")

Read shape : (2, 2, 2, 2, 2) from right to left as 2 rows and 2 columns // of 2 sets / of 2 sets /of 2sets 

In [ ]:
a = np.array([[[[[1,2],[3,4]],[[1,2],[3,4]]],[[[1,2],[3,4]],[[1,2],[3,4]]]],[[[[1,2],[3,4]],[[1,2],[3,4]]],[[[1,2],[3,4]],[[1,2],[3,4]]]]])
print(a)
print("============")
print("shape :" , a.shape)
print("============")
print("len(a.shape) :" , len(a.shape))
print("============")
print("a.size" , a.size)
print("============")

In [ ]:
a.dtype

In [ ]:
import sys
print(sys.modules)

In [ ]:
num_modules = len(sys.modules)
print(f"Number of loaded modules: {num_modules}")

In [ ]:
np.zeros(3)

In [ ]:
np.ones(2)

In [ ]:
np.zeros((2,3)) #2 rows 3 column : shape =2

In [ ]:
# Create an empty array with 2 elements
np.empty(2) 

In [ ]:
np.zeros((2,3,4)) #2 rows 3 column:4  : shape =3 dimension-rows-column

In [ ]:
s = (2,2)
np.zeros(s)


In [ ]:
s = (2,2,2)
np.zeros(s)

In [ ]:
s = (2,2,2,2)
np.zeros(s)

In [ ]:
np.ones_like(3)

In [ ]:
x = np.arange(6)
x = x.reshape((2, 3))
x

In [ ]:
np.ones_like(x) #same shape but with one

In [ ]:
np.ones(3)

In [ ]:
np.ones((3,2))

In [ ]:
np.empty(5) #Return a new array of given shape and type, without initializing entries

Unlike other array creation functions (e.g. `zeros`, `ones`, `full`),
`empty` does not initialize the values of the array, and may therefore be
marginally faster. However, the values stored in the newly allocated array
are arbitrary. For reproducible behavior, be sure to set each element of
the array before reading

NP.ARRANGE()
Return evenly spaced values within a given interval
Another stability issue is due to the internal implementation of
`numpy.arange`.
The actual step value used to populate the array is
``dtype(start + step) - dtype(start)`` and not `step`. Precision loss
can occur here, due to casting or due to using floating points when
`start` is much larger than `step`. This can lead to unexpected
behaviour. For example::

  >>> np.arange(0, 5, 0.5, dtype=int)
  array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
  >>> np.arange(-3, 3, 0.5, dtype=int)
  array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [7]:
np.arange(0, 5, 0.5, dtype=int) #start with 0 but less than 5 with increment of 0.5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.arange(-3, 3, 0.5, dtype=int) 

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

start with 2 but less than 9 with increment of 2

In [9]:
np.arange(2,9,2) 

array([2, 4, 6, 8])

np.arange(-3, 3, 0.5, dtype=int) generates a NumPy array with values starting from -3 up to (but not including) 3, with a step of 0.5, and then converts the elements to integers. Due to the dtype=int, the decimal part of each number is truncated, not rounded.

The length of the output might not be numerically stable.
---------------------------------------------------------

Another stability issue is due to the internal implementation of numpy.arange. The actual step value used to populate the array is dtype(start + step) - dtype(start) and not step. Precision loss can occur here, due to casting or due to using floating points when start is much larger than step. This can lead to unexpected behaviour. For example:

np.arange(0, 5, 0.5, dtype=int)
np.arange(-3, 3, 0.5, dtype=int)

In [11]:
np.arange(-3, 3, 0.5, dtype=int) 

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [12]:
np.arange(2,9,0.5) 

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5])

You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])


In [15]:
np.linspace(0, 10, num=5) #spaced out evently

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.linspace(0, 5, num=5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [17]:
np.linspace(0, 10, num=5,dtype=int) #spaced out evently

array([ 0,  2,  5,  7, 10])

In [18]:
np.ones(2,dtype=int64)

NameError: name 'int64' is not defined

In [19]:
np.ones(2,dtype=np.int64)

array([1, 1])